name: 'nbdime-git-diff'
description: 'Cleaner git diff of Ipython notebooks using nbdime'
runs:
  using: "composite"
  steps:
    - run: pip install nbdime ipython_genutils
      shell: bash
    - run: nbdime config-git --enable --global
      shell: bash
    - run: git diff HEAD^ HEAD
      shell: bash
branding:
  icon: 'git-merge'  
  color: 'blue'
